/**
 * Error code constants
 * Centralized error codes for consistent error handling
 */

export enum ErrorCode {
  // Validation Errors (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_FORMAT = 'INVALID_FORMAT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication Errors (401)
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // Authorization Errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Not Found Errors (404)
  NOT_FOUND = 'NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  LINK_NOT_FOUND = 'LINK_NOT_FOUND',
  CASE_NOT_FOUND = 'CASE_NOT_FOUND',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',

  // Conflict Errors (409)
  CONFLICT = 'CONFLICT',
  ROOM_ALREADY_EXISTS = 'ROOM_ALREADY_EXISTS',
  USER_ALREADY_IN_ROOM = 'USER_ALREADY_IN_ROOM',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',

  // Business Logic Errors (422)
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  ROOM_EXPIRED = 'ROOM_EXPIRED',
  ROOM_CLOSED = 'ROOM_CLOSED',
  ROOM_ALREADY_CLOSED = 'ROOM_ALREADY_CLOSED',
  ONE_TIME_LINK_USED = 'ONE_TIME_LINK_USED',
  LINK_EXPIRED = 'LINK_EXPIRED',
  INVALID_ROOM_STATUS = 'INVALID_ROOM_STATUS',
  MAX_PARTICIPANTS_REACHED = 'MAX_PARTICIPANTS_REACHED',

  // Server Errors (500)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  LIVEKIT_ERROR = 'LIVEKIT_ERROR',
  SMS_SERVICE_ERROR = 'SMS_SERVICE_ERROR',
  NOTIFICATION_SERVICE_ERROR = 'NOTIFICATION_SERVICE_ERROR',
}

/**
 * Map error codes to HTTP status codes
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  // 400 - Bad Request
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.INVALID_FORMAT]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,

  // 401 - Unauthorized
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,

  // 403 - Forbidden
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.ACCESS_DENIED]: 403,

  // 404 - Not Found
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.ROOM_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.LINK_NOT_FOUND]: 404,
  [ErrorCode.CASE_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_NOT_FOUND]: 404,

  // 409 - Conflict
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.ROOM_ALREADY_EXISTS]: 409,
  [ErrorCode.USER_ALREADY_IN_ROOM]: 409,
  [ErrorCode.DUPLICATE_ENTRY]: 409,

  // 422 - Unprocessable Entity
  [ErrorCode.BUSINESS_RULE_VIOLATION]: 422,
  [ErrorCode.ROOM_EXPIRED]: 422,
  [ErrorCode.ROOM_CLOSED]: 422,
  [ErrorCode.ROOM_ALREADY_CLOSED]: 422,
  [ErrorCode.ONE_TIME_LINK_USED]: 422,
  [ErrorCode.LINK_EXPIRED]: 422,
  [ErrorCode.INVALID_ROOM_STATUS]: 422,
  [ErrorCode.MAX_PARTICIPANTS_REACHED]: 422,

  // 500 - Internal Server Error
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 500,
  [ErrorCode.LIVEKIT_ERROR]: 500,
  [ErrorCode.SMS_SERVICE_ERROR]: 500,
  [ErrorCode.NOTIFICATION_SERVICE_ERROR]: 500,
};
